Allow setting separator and custom formatter per octet field
joyent/node-macaddr pull request #2
Opened 2021-06-16 18:49 UTC by cableray

In order to output various types easily, allow setting a custom separator, and allow providing a function to specify formatting.

Let me know what else is needed, please :)

2021-06-16 19:03 UTC, cableray commented
I think I'm going to change it so that the formatter doesn't override the padding, and then extract the default formatter to a function to simplify...

2021-06-16 19:30 UTC, cableray commented
I'd like to change the loop to a map, but that may be too much for this pr....

2021-06-16 21:11 UTC, bahamat commented
Still evaluating this, but at the very least it will need a version bump in package.json.

2021-06-18 21:39 UTC, cableray commented
> Still evaluating this, but at the very least it will need a version bump in package.json.

So, `0.1.0`? It's a non-breaking new feature, so minor bump? Given as it is currently at `0.0.1`, I didn't think it had been versioned before... Also, should I commit the auto reformatting of `package.json`? (Looks like npm re-ordered some packages)

2021-06-18 21:44 UTC, bahamat commented
Yeah, 0.1.0 is fine. There's only 3 commits so far in this repo so far. The first one was just creating the repo from our template, the second was ver 0.0.1, and the third commit was just updating the `make check` dependency, and no change in the behavior of the library.

And for the structure of `package.json`, making the diff minimal is easier to read, but other than that I don't have a strong opinion about it.

2021-06-18 21:57 UTC, bahamat requested changes
Ok, overall, things look pretty good with this. Only some small nits on whitespace.

Ensure that `make check` passes. After these and the version bump in package.json we'll be good to merge.

2021-06-18 21:57 UTC, bahamat commented on README.md
> +  octet as the argument and returns the formatted octet. If `zeroPad` is
Whitespace at end of lines 39 & 40 should be removed.

2021-06-18 21:57 UTC, bahamat commented on test/output.test.js
> +          str[0] + ' (with zeroPad=false)');
Indenting is not correct here.

2021-06-18 22:12 UTC, cableray commented
Oops, changed the spacing in brackets... let me revert that...

2021-06-18 23:34 UTC, bahamat approved these changes

2021-06-18 23:34 UTC, merged